name: llamar api news recientes cada 1m
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request GET \
          --url 'https://api-torii.vercel.app/api/v1/news/recientes' \
    
